### ISSUE TITLE
Consider moving this into webpack/webpack? 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack-contrib/babili-webpack-plugin#1]
Hey!!! My name is Sean, and I'm one of the core maintainers for webpack. By the way, nice job on creating something so quickly after the release of babili. 

Since webpack already owns UglifyJSPlugin, I'd love to see this also moved into our organization, whether it be added as core code, or a repo underneath the org. 

The webpack team wants to have optimization stuff as much "Out of the box" as possible for user configuration. 
1. Would you be willing to propose a RFC/Proposal/PullRequest for this on our repo? This plugin would probably be something that lives under webpack/lib/optimize.
2. If the movement on number 1 is slow, could the webpack org consume the repo, for separate development. 

Would you be open to either of these ideas? This will give us a lot more hands on in helping maintain and configuring the plugin for speed and performance, etc. 

Let me know what you think. And again thanks for your work.

**Comment by boopathi** [comment]
Sure. I don't have any concerns where the code lies. I can send a PR.

There are a few concerns that I think should be considered - 

1. name: https://github.com/babel/babili/issues/124
2. whether this plugin is the best way to add minification to build pipeline - https://github.com/babel/babel.github.io/pull/898#discussion_r76562069 . Either way this plugin will be useful. Also, any help should be really useful.

**Comment by TheLarkInn** [comment]
Awesome I'd like to discuss with the core team first their thoughts. I'll followup with you in about a week. Again thank you for the work and flexibility.

**Comment by jbucaran** [comment]
👋 Hi folks. Whatever happened to moving this plugin to webpack/webpack? 

Cheers.

**Comment by TheLarkInn** [comment]
We could think about moving this into webpack-contrib

**Comment by bebraw** [comment]
Any news on the transfer? I understand if you want to retain it under your account. No probs with that.

**Comment by boopathi** [comment]
Hey. Nothing like that. We can transfer it now.

How do we do it ? Do I give you access to the repo ? or do you give me access to the org for the transfer ?

**Comment by bebraw** [comment]
@boopathi I invited you to the org so you should be able to rename the repo to complete the transfer. Thanks a lot. 👍

**Comment by boopathi** [comment]
👍
