### ISSUE TITLE
How to stop UglifyJS from running on NODE_ENV=production?

### ISSUE THREAD

**Issue by selbekk** [webpack-contrib/babili-webpack-plugin#32]
I'm trying to use babili to do my minification instead of uglify whenever I run `webpack -p`. 

How do I do that? I can't seem to stop it.

**Comment by boopathi** [comment]
webpack -p is a shortform for webpack with `defineplugin = NODE_ENV=production` and `uglifyJsPlugin`.. So you should not use webpack -p and use the DefinePlugin and BabiliPlugin in your webpack config. 


```js
plugins: [
  new webpack.DefinePlugin({ 
    "process.env": { NODE_ENV: "'production'" }
  }),
  new BabiliPlugin()
]
```

**Comment by selbekk** [comment]
Oh so whenever you run webpack with the -p option Uglify gets run? That's a downer.

Thanks for the swift response! 🙌

**Comment by yattias** [comment]
Oh man, couple of hours I will never get back!

Thanks `-p` ! 😖

**Comment by joe1chen** [comment]
Damn this hit me as well. Spent several hours trying to figure this one out.

**Comment by akos-sereg** [comment]
me too :/
