### ISSUE TITLE
Handling Dynamic Imports

### ISSUE THREAD

**Issue by knpwrs** [webpack-contrib/babili-webpack-plugin#38]
I have the following `.babelrc`:

```json
{
  "presets": [
    "react",
    ["env", {
      "targets": {
        "browsers": ["Chrome 58"]
      },
      "modules": false
    }]
  ],
  "plugins": [
    "ramda",
    "syntax-dynamic-import"
  ]
}
```

This works for my development build, but my production build with this plugin for babili chokes on a dynamic import (complaining about an unexpected token).

Am I doing something wrong? Is this plugin supposed to inherit my `.babelrc` and pick up `babel-plugin-syntax-dynamic-import`.

**Comment by knpwrs** [comment]
My proposed solution would be either to make this line ( https://github.com/webpack-contrib/babili-webpack-plugin/blob/e379daf125821d3c9ce7fb7e39640be0e7324ae3/src/index.js#L74 ) configurable or add `babel-plugin-syntax-dynamic-import` as a dependency for this plugin. Thoughts?

**Comment by boopathi** [comment]
Why is the functional import syntax pass through this plugin in the first place ?. Webpack replaces `import()` to something like `__webpack_require__.` and babili sees this. Isn't it?

**Comment by knpwrs** [comment]
@boopathi see my explanation in #39.
