### ISSUE TITLE
Invalid option "test" bug

### ISSUE THREAD

**Issue by ugo-buonadonna** [webpack-contrib/babili-webpack-plugin#41]
Hi, 

When using the plugin like that: 
```
new BabiliPlugin({
      options: {
        test: /\.jsx?$/i,
        comments: false,
        sourceMap: true
      }
    })
```
and then running webpack compilation, this error shows up in the terminal:
`ERROR: Invalid option "test"`

This error is actually thrown by the `babel-preset-babili` module.

I had to revert to the 0.0.11 version in order to make it work again.

I'm using webpack version 2.6.0.

Thanks

**Comment by szimek** [comment]
Shouldn't it actually be:
```js
new BabiliPlugin({}, {
  test: /\.jsx?$/i,
  comments: false,
  sourceMap: true,
})
```
? According to docs it's `new BabiliPlugin(babiliOptions, overrides)`, where [overrides](https://github.com/webpack-contrib/babili-webpack-plugin#overrides) are what you're setting.

**Comment by boopathi** [comment]
Closing the issue as it's already answered.
