### ISSUE TITLE
Tree shaking not working?

### ISSUE THREAD

**Issue by damianobarbati** [webpack-contrib/babili-webpack-plugin#43]
I'm seeing the full lodash library instead of just the map function in my vendor chunk in the compiled /build/visitor/vendor.min.js.
Shouldn't just the map function be there with the following?
```
import { map } from 'lodash';
console.log(map([1,2], value => value**2));
```

Repro here => https://github.com/damianobarbati/repro-babili-tree-shaking
To reproduce:
`git clone https://github.com/damianobarbati/repro-babili-tree-shaking`
`yarn install`
`yarn serve:dev` #ctrl+c to close logging
`yarn build:prod` #run webpack and babili

**Comment by boopathi** [comment]
This plugin doesn't do TreeShaking.

Aside: You're importing the CommonJS version of lodash where CommonJS is NOT TreeShakable. 

You can either use the ESModule version of that - [lodash-es](https://www.npmjs.com/package/lodash-es)

```js
import {map} from "lodash-es";
```

or you can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash).
