### ISSUE TITLE
Invalid option 'babili'

### ISSUE THREAD

**Issue by davisford** [webpack-contrib/babili-webpack-plugin#45]
Hi, I've tried several ways to configure this plugin -- I either hit the [Out Of Memory Issue](https://github.com/babel/babili/issues/332) with Babili itself (using all default options), or when I do try to pass options, I consistently get some error about an option property I *thought* was valid, and it doesn't minify or mangle anything.

Here's example output showing the latter:

```
 [372] ./bo/forms/payments.js 21.9 kB {0} [built]
 [414] ./pos.css 1.02 kB {1} [built]
 [555] ./boindex.js 6.28 kB {0} [built]
 [589] ./posindex.js 2.15 kB {1} [built]
    + 637 hidden modules

ERROR in Invalid option "presets"

ERROR in Invalid option "presets"

ERROR in Invalid option "presets"

ERROR in Invalid option "presets"
```

I've scoured github issues trying to find the correct way to configure the plugin.  I must be missing something with the [babili-preset-options](https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options) project.  

When I try to pass in some simple preset options, no matter what construction I make, it errors out and won't minify, etc.

```javascript
config.plugins.push(new BabiliPlugin({
            "presets": [["babili", {
            "evaluate": false,
            "mangle": true
          }]]
        
      }, {
        test: /\.js$/i,
        comments: false,
        sourceMap: true
      }));
```

Could someone advise on the correct way to configure this plugin?

**Comment by boopathi** [comment]
The format is 

```js
config.plugins.push(new BabiliPlugin({
  mangle: true,
  evaluate: true,
  // and all options that you'd pass to the preset
}, {
  test: /\.js$/i,
  comments: false,
  sourceMap: true
});
```
