### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jason-krypton** [webpack-contrib/babili-webpack-plugin#47]
`babel-preset-babili` released a new version a few days ago that fixes some breaking bugs. Can we get a new release on babili-webpack-plugin pointing its npm depedencies at 0.1.3? 

Thanks!

**Comment by raitucarp** [comment]
+1

FYI, the new release of babili is 0.1.4.

**Comment by anilanar** [comment]
Any updates? If you lack time for making releases, I'd be more than glad to help. If there are some concerns for making a new release, it would be great to share them.

**Comment by evilebottnawi** [comment]
we can do this asap, don't worry

**Comment by boopathi** [comment]
Published 0.1.2 with babili@0.1.4
